# Generated by Django 5.0.4 on 2024-05-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_subject_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='SubjectMark',
        ),
    ]
